AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LambdaWithSNS:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: s3://<bucket name>/<key file>
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::xxxxxxx:role/lambda_basic_execute'
     
  
  SNS1:
    Type: 'AWS::SNS::Subscription'
    Properties:
      FilterPolicy:  '{"Filterby": ["SomeValue"] }'
      TopicArn: 'arn:aws:sns:us-east-1:xxxxxxxx:SomeTopic'
      Protocol: lambda
      Endpoint: !GetAtt LambdaWithSNS.Arn
